[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["python -m venv /opt/venv", "/opt/venv/bin/pip install -r requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "/opt/venv/bin/python main.py"

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"
